package com.hackerearth.mphasis.mhc7.brahmastra.biz.cep;

// list any import classes here.
import com.hackerearth.mphasis.mhc7.brahmastra.biz.vo.BudhaEvent;
import com.hackerearth.mphasis.mhc7.brahmastra.biz.vo.BudhaEventCorrelation;

declare BudhaEvent
	@role(event)
	@expires(20s)
	@timestamp (eventDestinationTimestamp)
end

declare BudhaEventCorrelation
	@role(event)
	@expires(20s)
	@timestamp (eventDestinationTimestamp)
end

global Long startTime;
global Long startMemory;
global Long totalFactCount;
global java.util.HashMap threatMap; 

// use case 01
// detect if there are more than ten port or ip scan attempts from the same ip address (and port) 
// to the destination ip address (and multiple ports) in the given window
rule "Port and IP Scan Event Processing Initial"
dialect "mvel"
no-loop
  when
    e1: BudhaEvent(eventType == "port and ip scan") over window:time(10s) 
    not BudhaEventCorrelation(eventSourceIp == e1.eventSourceIp, eventDestinationIp == e1.eventDestinationIp, eventSourcePort == e1.eventSourcePort)  
  then
	  BudhaEventCorrelation plec = new BudhaEventCorrelation();
	  plec.setEventSourceIp(e1.eventSourceIp);
	  plec.setEventDestinationIp(e1.eventDestinationIp);
	  plec.setEventSourcePort(e1.eventSourcePort);
	  plec.setEventDestinationPort(e1.eventDestinationPort);
	  plec.setEventCorrelation(0);
	  insert(plec);
end


rule "Port and IP Scan Event Processing Correlation"
dialect "mvel"
no-loop
  when
    e1: BudhaEvent(eventType == "port and ip scan") over window:time(10s) 
    ce: BudhaEventCorrelation(eventSourceIp == e1.eventSourceIp, eventDestinationIp == e1.eventDestinationIp, eventSourcePort == e1.eventSourcePort, $eventCorr : eventCorrelation >= 0)
  then
  	$eventCorr++;
    ce.eventCorrelation=$eventCorr;
    if(ce.eventCorrelation >= 10) {
    	System.out.println("");
		System.out.println("+++++++++++++++ USE CASE 01 +++++++++++++++");
		System.out.println("SOURCE INET: " + ce.eventSourceIp);
		System.out.println("SOURCE PORT: " + ce.eventSourcePort);
		System.out.println("DESTIN INET: " + ce.eventDestinationIp);
		System.out.println("EVENT  ACTN: " + "port and ip scan");
		System.out.println("TIMESTAMP  : " + new java.util.Date(ce.eventDestinationTimestamp));
		System.out.println("OCCURENCES : " + $eventCorr);
		System.out.println("+++++++++++++++++++++++++++++++++++++++++++");
		System.out.println("");
    }  	
    update( ce );
    threatMap.put(new java.util.Date(), ce);
end





